export const SAMPLES = [
  {
    name: "transform2d — shear (animated identity→M)",
    raw: {
      v: 1,
      kind: "transform2d",
      title: "גזירה (shear): [[1, 0.8],[0, 1]]",
      matrix: [
        [1, 0.8],
        [0, 1],
      ],
      show: { grid: true, basis: true },
      vectors: [{ x: 2, y: 1, label: "v", color: "warning" }],
      range: 4,
    },
  },
  {
    name: "transform2d — rotation (no real eigenvectors)",
    raw: {
      v: 1,
      kind: "transform2d",
      title: "סיבוב 90°: אין ערכים עצמיים ממשיים",
      matrix: [
        [0, -1],
        [1, 0],
      ],
      show: { grid: true, basis: true, eigen: true },
      range: 3,
    },
  },
  {
    name: "transform2d — symmetric + eigenvectors + unit circle",
    raw: {
      v: 1,
      kind: "transform2d",
      title: "מטריצה סימטרית [[2,1],[1,2]] — וקטורים עצמיים",
      matrix: [
        [2, 1],
        [1, 2],
      ],
      show: { grid: true, basis: true, eigen: true, unitCircle: true },
      range: 4,
    },
  },
  {
    name: "graph — weighted network + shortest path (Dijkstra)",
    raw: {
      v: 1,
      kind: "graph",
      title: "מסלול קצר ביותר A→E",
      directed: false,
      nodes: [
        { id: "A", label: "A", color: "accent" },
        { id: "B", label: "B" },
        { id: "C", label: "C" },
        { id: "D", label: "D" },
        { id: "E", label: "E", color: "success" },
      ],
      edges: [
        { from: "A", to: "B", weight: 4 },
        { from: "A", to: "C", weight: 2 },
        { from: "C", to: "B", weight: 1 },
        { from: "B", to: "D", weight: 5 },
        { from: "C", to: "D", weight: 8 },
        { from: "D", to: "E", weight: 3 },
        { from: "C", to: "E", weight: 10 },
      ],
      highlight: {
        nodes: ["A", "C", "B", "D", "E"],
        edges: [
          ["A", "C"],
          ["C", "B"],
          ["B", "D"],
          ["D", "E"],
        ],
      },
    },
  },
  {
    name: "graph — directed (task dependencies / DAG)",
    raw: {
      v: 1,
      kind: "graph",
      title: "גרף מכוון: קדימויות משימות",
      directed: true,
      nodes: [
        { id: "t1", label: "1" },
        { id: "t2", label: "2" },
        { id: "t3", label: "3" },
        { id: "t4", label: "4" },
        { id: "t5", label: "5" },
      ],
      edges: [
        { from: "t1", to: "t2" },
        { from: "t1", to: "t3" },
        { from: "t2", to: "t4" },
        { from: "t3", to: "t4" },
        { from: "t4", to: "t5" },
      ],
    },
  },
  {
    name: "distribution — normal right tail (z-test)",
    raw: {
      v: 1,
      kind: "distribution",
      title: "מבחן חד-צדדי: z* = 1.64",
      dist: "normal",
      params: { mu: 0, sigma: 1 },
      shade: { from: 1.64, to: null, label: "α = 0.05" },
      marks: [{ x: 1.64, label: "z*", color: "warning" }],
      xRange: [-4, 4],
    },
  },
  {
    name: "distribution — t distribution (two-tailed)",
    raw: {
      v: 1,
      kind: "distribution",
      title: "התפלגות t (df=8)",
      dist: "t",
      params: { df: 8 },
      shade: { from: 2.31, to: null, label: "0.025" },
      marks: [
        { x: 2.31, label: "t*", color: "warning" },
        { x: -2.31, label: "−t*", color: "warning" },
      ],
    },
  },
  {
    name: "distribution — chi-squared",
    raw: {
      v: 1,
      kind: "distribution",
      title: "התפלגות χ² (df=4)",
      dist: "chisq",
      params: { df: 4 },
      shade: { from: 9.49, to: null, label: "α = 0.05" },
      marks: [{ x: 9.49, label: "χ²*", color: "warning" }],
    },
  },
  {
    name: "parametric-plot — RC discharge",
    raw: {
      v: 1,
      kind: "parametric-plot",
      title: "פריקת קבל RC",
      x: { var: "t", min: 0, max: 10, label: "זמן (s)" },
      params: [
        {
          var: "R",
          min: 2,
          max: 50,
          default: 10,
          step: 1,
          label: "התנגדות",
          unit: "Ω",
        },
      ],
      curves: [{ label: "Q(t)", expr: "3*exp(-t/(R*0.1))", color: "accent" }],
    },
  },
  {
    name: "function-compare — growth rates",
    raw: {
      v: 1,
      kind: "function-compare",
      title: "קצב גדילה: ליניארי מול ריבועי מול מעריכי",
      x: { var: "x", min: 0, max: 10, label: "n" },
      curves: [
        { label: "linear", expr: "x", color: "accent" },
        { label: "quadratic", expr: "x^2/10", color: "evTeal" },
        { label: "exponential", expr: "exp(x/3)/3", color: "warning" },
      ],
    },
  },
  {
    name: "parametric-plot — ANIMATED traveling wave (play/pause)",
    raw: {
      v: 1,
      kind: "parametric-plot",
      title: "גל מתקדם: y = sin(x − φ)",
      x: { var: "x", min: 0, max: 12.566, label: "x" },
      y: { min: -1.4, max: 1.4 },
      params: [{ var: "phi", min: 0, max: 6.283, default: 0, label: "פאזה φ" }],
      curves: [{ label: "y", expr: "sin(x - phi)", color: "accent" }],
      animate: { param: "phi", period: 4, loop: "cycle" },
    },
  },
  {
    name: "parametric-plot — ANIMATED damping (bounce)",
    raw: {
      v: 1,
      kind: "parametric-plot",
      title: "דעיכה: y = e^(−b·x)·cos(3x)",
      x: { var: "x", min: 0, max: 8, label: "x" },
      y: { min: -1.1, max: 1.1 },
      params: [
        {
          var: "b",
          min: 0,
          max: 1,
          default: 0.1,
          step: 0.01,
          label: "מקדם דעיכה b",
        },
      ],
      curves: [{ label: "y", expr: "exp(-b*x)*cos(3*x)", color: "evTeal" }],
      animate: { param: "b", period: 5, loop: "bounce" },
    },
  },
  {
    name: "region 'under' — area / integral (p-value tail)",
    raw: {
      v: 1,
      kind: "parametric-plot",
      title: "התפלגות נורמלית — שטח = הסתברות",
      x: { var: "x", min: 0, max: 10, label: "x" },
      curves: [{ label: "f", expr: "exp(-((x-5)^2)/2)", color: "accent" }],
      regions: [
        {
          type: "under",
          curve: "f",
          from: 3,
          to: 5,
          color: "evPurple",
          label: "שטח",
        },
      ],
    },
  },
  {
    name: "region 'between' — consumer/producer surplus",
    raw: {
      v: 1,
      kind: "function-compare",
      title: "ביקוש מול היצע — עודף",
      x: { var: "q", min: 0, max: 8, label: "כמות" },
      curves: [
        { label: "ביקוש", expr: "10-q", color: "accent" },
        { label: "היצע", expr: "2+q", color: "evTeal" },
      ],
      regions: [
        {
          type: "between",
          curve: "ביקוש",
          curve2: "היצע",
          from: 0,
          to: 4,
          color: "success",
          label: "עודף",
        },
      ],
    },
  },
  {
    name: "chart 'bar' — grouped categories",
    raw: {
      v: 1,
      kind: "chart",
      chartType: "bar",
      title: "ציונים ממוצעים לפי סמסטר",
      labels: ["מבוא", "נתונים", "אלגוריתמים"],
      series: [
        { name: "2023", color: "accent", data: [78, 71, 65] },
        { name: "2024", color: "evTeal", data: [82, 76, 73] },
      ],
      y: { label: "ציון" },
    },
  },
  {
    name: "chart 'pie' — distribution",
    raw: {
      v: 1,
      kind: "chart",
      chartType: "pie",
      title: "התפלגות הרכב האטמוספרה",
      labels: ["חנקן", "חמצן", "ארגון", "אחר"],
      series: [{ data: [78, 21, 0.9, 0.1] }],
    },
  },
  {
    name: "chart 'line' — trend",
    raw: {
      v: 1,
      kind: "chart",
      chartType: "line",
      title: "טמפרטורה לאורך השבוע",
      labels: ["א", "ב", "ג", "ד", "ה", "ו", "ש"],
      series: [
        { name: "מקס", color: "warning", data: [28, 30, 31, 29, 27, 26, 25] },
        { name: "מין", color: "evTeal", data: [18, 19, 20, 19, 17, 16, 15] },
      ],
      y: { label: "°C" },
    },
  },
  {
    name: "chart 'scatter' — correlation",
    raw: {
      v: 1,
      kind: "chart",
      chartType: "scatter",
      title: "שעות לימוד מול ציון",
      x: { label: "שעות" },
      y: { label: "ציון" },
      series: [
        {
          name: "תצפיות",
          color: "evPurple",
          points: [
            { x: 1, y: 55 },
            { x: 2, y: 60 },
            { x: 3, y: 68 },
            { x: 4, y: 72 },
            { x: 5, y: 80 },
            { x: 6, y: 79 },
            { x: 7, y: 88 },
            { x: 8, y: 92 },
          ],
        },
      ],
    },
  },
  {
    name: "table — truth table (∧)",
    raw: {
      v: 1,
      kind: "table",
      title: "טבלת אמת: וגם (AND)",
      headerRow: true,
      rows: [
        ["p", "q", "p ∧ q"],
        ["T", "T", "T"],
        ["T", "F", "F"],
        ["F", "T", "F"],
        ["F", "F", "F"],
      ],
      highlight: [{ r: 1, c: 2, color: "success" }],
    },
  },
  {
    name: "table — Punnett square",
    raw: {
      v: 1,
      kind: "table",
      title: "ריבוע פאנט: Aa × Aa",
      headerRow: true,
      headerCol: true,
      rows: [
        ["", "A", "a"],
        ["A", "AA", "Aa"],
        ["a", "Aa", "aa"],
      ],
      highlight: [{ r: 2, c: 2, color: "warning" }],
    },
  },
  {
    name: "tree — binary search tree",
    raw: {
      v: 1,
      kind: "tree",
      title: "עץ חיפוש בינארי",
      nodes: [
        { id: "8", label: "8", color: "accent" },
        { id: "3", label: "3", parent: "8" },
        { id: "10", label: "10", parent: "8" },
        { id: "1", label: "1", parent: "3" },
        { id: "6", label: "6", parent: "3" },
        { id: "14", label: "14", parent: "10", color: "evTeal" },
        { id: "4", label: "4", parent: "6" },
        { id: "7", label: "7", parent: "6" },
      ],
    },
  },
  {
    name: "geometry2d — vector addition",
    raw: {
      v: 1,
      kind: "geometry2d",
      title: "חיבור וקטורים: a + b",
      xRange: [-1, 6],
      yRange: [-1, 6],
      items: [
        {
          type: "vector",
          x1: 0,
          y1: 0,
          x2: 4,
          y2: 1,
          label: "a",
          color: "accent",
        },
        {
          type: "vector",
          x1: 0,
          y1: 0,
          x2: 1,
          y2: 3,
          label: "b",
          color: "evTeal",
        },
        {
          type: "vector",
          x1: 0,
          y1: 0,
          x2: 5,
          y2: 4,
          label: "a+b",
          color: "warning",
        },
        {
          type: "segment",
          x1: 4,
          y1: 1,
          x2: 5,
          y2: 4,
          color: "textMuted",
          dashed: true,
        },
        {
          type: "segment",
          x1: 1,
          y1: 3,
          x2: 5,
          y2: 4,
          color: "textMuted",
          dashed: true,
        },
      ],
    },
  },
  {
    name: "slope-field — direction field y' = f(x,y)",
    raw: {
      v: 1,
      kind: "slope-field",
      title: "שדה כיוונים: y' = x − y",
      expr: "x - y",
      xRange: [-3, 3],
      yRange: [-3, 3],
    },
  },
  {
    name: "geometry2d — free-body diagram",
    raw: {
      v: 1,
      kind: "geometry2d",
      title: "דיאגרמת כוחות על גוף",
      xRange: [-4, 4],
      yRange: [-4, 4],
      grid: false,
      axes: false,
      items: [
        {
          type: "polygon",
          points: [
            [-1, -1],
            [1, -1],
            [1, 1],
            [-1, 1],
          ],
          fill: true,
          color: "textMuted",
        },
        {
          type: "vector",
          x1: 0,
          y1: 0,
          x2: 0,
          y2: 3,
          label: "N",
          color: "accent",
        },
        {
          type: "vector",
          x1: 0,
          y1: 0,
          x2: 0,
          y2: -3,
          label: "mg",
          color: "warning",
        },
        {
          type: "vector",
          x1: 0,
          y1: 0,
          x2: 3,
          y2: 0,
          label: "F",
          color: "evGreen",
        },
        {
          type: "vector",
          x1: 0,
          y1: 0,
          x2: -2,
          y2: 0,
          label: "f",
          color: "evPurple",
        },
      ],
    },
  },
  {
    name: "geometry2d — parabola + tangent",
    raw: {
      v: 1,
      kind: "geometry2d",
      title: "משיק לפרבולה y=x² בנקודה (1,1)",
      xRange: [-3, 3],
      yRange: [-1, 5],
      items: [
        { type: "function", expr: "x^2", color: "accent" },
        {
          type: "segment",
          x1: -1,
          y1: -1,
          x2: 3,
          y2: 3,
          color: "warning",
          label: "y=2x-1",
        },
        { type: "point", x: 1, y: 1, label: "P" },
      ],
    },
  },
  {
    name: "numberline — compound inequality",
    raw: {
      v: 1,
      kind: "numberline",
      title: "פתרון: -1 < x ≤ 3",
      min: -5,
      max: 6,
      points: [{ x: 0, label: "0" }],
      intervals: [
        {
          from: -1,
          to: 3,
          color: "success",
          openFrom: true,
          openTo: false,
          label: "-1 < x ≤ 3",
        },
      ],
    },
  },
  {
    name: "numberline — sign chart",
    raw: {
      v: 1,
      kind: "numberline",
      title: "סימן של (x-1)(x+2)",
      min: -4,
      max: 4,
      points: [
        { x: -2, label: "-2", color: "warning", open: true },
        { x: 1, label: "1", color: "warning", open: true },
      ],
      intervals: [
        { from: -4, to: -2, color: "evTeal", openTo: true, label: "+" },
        {
          from: -2,
          to: 1,
          color: "evPurple",
          openFrom: true,
          openTo: true,
          label: "−",
        },
        { from: 1, to: 4, color: "evTeal", openFrom: true, label: "+" },
      ],
    },
  },
  {
    name: "timeline — software lifecycle",
    raw: {
      v: 1,
      kind: "timeline",
      title: "מחזור חיי פיתוח תוכנה",
      events: [
        { label: "ניתוח דרישות", at: "שלב 1" },
        { label: "עיצוב", at: "שלב 2" },
        { label: "מימוש", at: "שלב 3" },
        { label: "בדיקות", at: "שלב 4" },
        { label: "פריסה", at: "שלב 5" },
        { label: "תחזוקה", at: "שלב 6" },
      ],
    },
  },
  {
    name: "venn — two sets (set operations)",
    raw: {
      v: 1,
      kind: "venn",
      title: "A ∪ B",
      sets: [
        { label: "A", color: "accent" },
        { label: "B", color: "evTeal" },
      ],
      regions: [
        { cells: "A", label: "רק A" },
        { cells: "AB", label: "A ∩ B" },
        { cells: "B", label: "רק B" },
      ],
    },
  },
  {
    name: "venn — three sets",
    raw: {
      v: 1,
      kind: "venn",
      title: "תכונות מספרים",
      sets: [
        { label: "זוגי", color: "accent" },
        { label: "ראשוני", color: "evTeal" },
        { label: "< 10", color: "warning" },
      ],
      regions: [
        { cells: "A", label: "12" },
        { cells: "B", label: "11" },
        { cells: "C", label: "9" },
        { cells: "AC", label: "4,6,8" },
        { cells: "BC", label: "3,5,7" },
        { cells: "AB", label: "—" },
        { cells: "ABC", label: "2" },
      ],
    },
  },
  {
    name: "diagram — state machine",
    raw: {
      v: 1,
      kind: "diagram",
      title: "מכונת מצבים: TCP",
      nodes: [
        { id: "closed", label: "CLOSED", x: 0.12, y: 0.5, color: "textMuted" },
        { id: "listen", label: "LISTEN", x: 0.42, y: 0.2, color: "accent" },
        { id: "syn", label: "SYN-RCVD", x: 0.72, y: 0.5, color: "evTeal" },
        { id: "est", label: "ESTABLISHED", x: 0.9, y: 0.85, color: "success" },
      ],
      edges: [
        { from: "closed", to: "listen", label: "passive open" },
        { from: "listen", to: "syn", label: "SYN" },
        { from: "syn", to: "est", label: "ACK" },
      ],
    },
  },
  {
    name: "memory-sim — interactive simulator (buttons + counters)",
    raw: {
      v: 1,
      kind: "memory-sim",
      title: "סימולטור Stack / Heap",
      code: [
        "void main() {",
        "  int age = 25;",
        "  User u1 = new User();",
        "  u1 = null;",
        "}",
      ],
      frames: [{ id: "main", label: "main()" }],
      slots: [
        { id: "age", frame: "main", label: "age = 25", type: "primitive" },
        { id: "u1", frame: "main", label: "u1 = ref", type: "reference" },
      ],
      objects: [{ id: "obj", label: "User Object" }],
      refs: [{ id: "r1", from: "u1", to: "obj", label: "reference" }],
      steps: [
        {
          line: 1,
          caption: "ערך פרימיטיבי נשמר ישירות במחסנית.",
          show: ["main", "age"],
          focus: ["age"],
        },
        {
          line: 2,
          caption: "האובייקט נוצר בערימה; המשתנה מחזיק התייחסות אליו.",
          show: ["main", "age", "u1", "obj", "r1"],
          focus: ["u1", "r1", "obj"],
        },
        {
          line: 3,
          caption: "u1 = null — אין יותר התייחסות; האובייקט מועמד לאיסוף זבל.",
          show: ["main", "age", "u1"],
          focus: ["u1"],
        },
      ],
      buttons: [
        { label: "הקצאה במחסנית", step: 0 },
        { label: "צור אובייקט", step: 1 },
        { label: "נתק התייחסות", step: 2 },
      ],
    },
  },
  {
    name: "bracket-sim — live bracket-matching stack",
    raw: {
      v: 1,
      kind: "bracket-sim",
      title: "בדיקת תקינות סוגריים עם מחסנית",
      input: "{[(a+b)*c]}",
      examples: ["(()", "()", "[)", "[c-d]*(a+b)", "{[()]}"],
    },
  },
  {
    name: "geometry2d — integration region (disk D + axis, the tolerated shapes)",
    raw: {
      v: 1,
      kind: "geometry2d",
      title: "התחום D: (x−1)² + y² ≤ 1",
      xRange: [-1.5, 3.5],
      yRange: [-1.8, 3],
      points: [{ x: 1, y: 0, label: "מרכז (1,0)" }],
      circles: [
        {
          center: { x: 1, y: 0 },
          radius: 1,
          color: "evTeal",
          label: "(x−1)²+y²=1",
        },
      ],
      regions: [
        {
          type: "circle",
          center: { x: 1, y: 0 },
          radius: 1,
          color: "success",
          label: "D",
        },
      ],
      lines: [
        {
          x1: -1.5,
          y1: 2,
          x2: 3.5,
          y2: 2,
          color: "accent",
          dashed: true,
          label: "y=2",
        },
      ],
    },
  },
  {
    name: "geometry2d — Cartesian full annulus 1≤x²+y²≤4 (pairs with polar below)",
    raw: {
      v: 1,
      kind: "geometry2d",
      title: "1 ≤ x² + y² ≤ 4",
      xRange: [-2.6, 2.6],
      yRange: [-2.6, 2.6],
      xLabel: "x",
      yLabel: "y",
      items: [{ type: "sector", r1: 1, r2: 2, fill: true, color: "success" }],
    },
  },
  {
    name: "geometry2d — POLAR grid: full annulus 1≤r≤2, 0≤θ<2π",
    raw: {
      v: 1,
      kind: "geometry2d",
      title: "1 ≤ r ≤ 2,  0 ≤ θ < 2π",
      grid: "polar",
      xRange: [-2.6, 2.6],
      yRange: [-2.6, 2.6],
      items: [{ type: "sector", r1: 1, r2: 2, fill: true, color: "success" }],
    },
  },
  {
    name: "geometry2d — POLAR grid: cardioid r = 1 + cos θ",
    raw: {
      v: 1,
      kind: "geometry2d",
      title: "עלעלת (cardioid): r = 1 + cos θ",
      grid: "polar",
      xRange: [-0.8, 2.4],
      yRange: [-1.6, 1.6],
      items: [
        {
          type: "parametric",
          x: "(1+cos(t))*cos(t)",
          y: "(1+cos(t))*sin(t)",
          t: [0, 6.2832],
          color: "accent",
          label: "r=1+cos θ",
        },
      ],
    },
  },
  {
    name: "surface3d — double integral over an elliptic region",
    raw: {
      v: 1,
      kind: "surface3d",
      title: "∬_D e^(1-(x²/36+y²/4)) dA",
      xRange: [-15, 15],
      yRange: [-10, 10],
      zRange: [0, 3],
      surfaces: [{ expr: "exp(1-(x^2/36+y^2/4))", color: "evTeal" }],
      region: {
        base: { type: "ellipse", cx: 0, cy: 0, a: 6, b: 2 },
        color: "success",
        label: "D",
      },
    },
  },
  {
    name: "surface3d — paraboloid over a 'between curves' region",
    raw: {
      v: 1,
      kind: "surface3d",
      title: "נפח מתחת ל-z=x²+y² מעל 0≤y≤x",
      xRange: [-1, 3],
      yRange: [-1, 3],
      surfaces: [{ expr: "x^2+y^2", color: "accent" }],
      region: {
        base: { type: "between", x: [0, 2], lower: "0", upper: "x" },
        color: "warning",
      },
    },
  },
  {
    name: "surface3d — parametric sphere (aspect:data, no integrand)",
    raw: {
      v: 1,
      kind: "surface3d",
      title: "ספירה x²+y²+z²=1",
      aspect: "data",
      surfaces: [
        {
          x: "cos(u)*sin(v)",
          y: "sin(u)*sin(v)",
          z: "cos(v)",
          uRange: [0, 6.2832],
          vRange: [0, 3.1416],
          color: "evPurple",
        },
      ],
    },
  },
  {
    name: "surface3d — type-II region (x between curves of y)",
    raw: {
      v: 1,
      kind: "surface3d",
      title: "∬ מעל 0≤x≤y, 0≤y≤2",
      xRange: [-0.5, 2.5],
      yRange: [-0.5, 2.5],
      surfaces: [{ expr: "x+y", color: "evTeal" }],
      region: {
        base: { type: "between-y", y: [0, 2], left: "0", right: "y" },
        color: "success",
      },
    },
  },
  {
    // Volume BETWEEN two surfaces over a disk: the region's lateral wall IS the cylinder,
    // so this yields 4 toggles — upper / lower / boundary wall / the volume itself.
    name: "surface3d — volume between two surfaces over a disk (4 toggles)",
    raw: {
      v: 1,
      kind: "surface3d",
      title: "נפח בין שני משטחים מעל גליל",
      xRange: [-1.4, 1.4],
      yRange: [-1.4, 1.4],
      surfaces: [
        { expr: "18+x^2", color: "accent", label: "משטח עליון" },
        { expr: "8*x+5*y", color: "evTeal", label: "משטח תחתון" },
      ],
      region: {
        surface: "18+x^2",
        lower: "8*x+5*y",
        base: { type: "ellipse", cx: 0, cy: 0, a: 1, b: 1 },
        color: "success",
        label: "גוף מלא",
      },
    },
  },
  {
    name: "geometry2d — parametric curve (Lissajous)",
    raw: {
      v: 1,
      kind: "geometry2d",
      title: "עקומת ליסז'ו x=sin3t, y=sin2t",
      xRange: [-1.3, 1.3],
      yRange: [-1.3, 1.3],
      parametrics: [
        { x: "sin(3*t)", y: "sin(2*t)", t: [0, 6.2832], color: "accent" },
      ],
    },
  },
  {
    name: "geometry2d — TRACER: projectile motion (moving dot + trail)",
    raw: {
      v: 1,
      kind: "geometry2d",
      title: "זריקה אופקית-אלכסונית",
      xRange: [-0.3, 3.3],
      yRange: [-0.3, 1.5],
      grid: true,
      axes: true,
      items: [
        {
          type: "parametric",
          x: "3*t",
          y: "4.9*t*(1 - t)",
          t: [0, 1],
          color: "accent",
          label: "m",
          trace: true,
        },
      ],
    },
  },
  {
    name: "geometry2d — TRACER: planet orbit (ellipse)",
    raw: {
      v: 1,
      kind: "geometry2d",
      title: "מסלול אליפטי",
      xRange: [-2.6, 2.6],
      yRange: [-1.9, 1.9],
      grid: false,
      axes: true,
      items: [
        { type: "point", x: 0, y: 0, label: "★", color: "warning" },
        {
          type: "parametric",
          x: "2.2*cos(t)",
          y: "1.3*sin(t)",
          t: [0, 6.2832],
          color: "evTeal",
          label: "◐",
          trace: true,
        },
      ],
    },
  },
  {
    name: "geometry2d — 2D ellipse region",
    raw: {
      v: 1,
      kind: "geometry2d",
      title: "אזור אליפטי x²/36+y²/4≤1",
      xRange: [-8, 8],
      yRange: [-4, 4],
      ellipses: [
        {
          cx: 0,
          cy: 0,
          rx: 6,
          ry: 2,
          color: "success",
          fill: true,
          label: "D",
        },
      ],
    },
  },
  {
    name: "logic-circuit — half adder (XOR + AND, auto truth table)",
    raw: {
      v: 1,
      kind: "logic-circuit",
      title: "מחצית מסכם (Half Adder)",
      inputs: [{ id: "A", value: 1 }, { id: "B" }],
      gates: [
        { id: "S", type: "xor", inputs: ["A", "B"] },
        { id: "C", type: "and", inputs: ["A", "B"] },
      ],
      outputs: [
        { from: "S", label: "Sum" },
        { from: "C", label: "Carry" },
      ],
    },
  },
  {
    name: "logic-circuit — full adder (multi-level, inverting gates)",
    raw: {
      v: 1,
      kind: "logic-circuit",
      title: "מסכם מלא (Full Adder)",
      inputs: [{ id: "A", value: 1 }, { id: "B", value: 1 }, { id: "Cin" }],
      gates: [
        { id: "x1", type: "xor", inputs: ["A", "B"] },
        { id: "S", type: "xor", inputs: ["x1", "Cin"], label: "sum" },
        { id: "a1", type: "and", inputs: ["x1", "Cin"] },
        { id: "a2", type: "and", inputs: ["A", "B"] },
        { id: "Cout", type: "or", inputs: ["a1", "a2"] },
      ],
      outputs: [
        { from: "S", label: "Sum" },
        { from: "Cout", label: "Cout" },
      ],
    },
  },
  {
    name: "logic-circuit — NAND/NOR/XNOR glyphs + auto-derived output",
    raw: {
      v: 1,
      kind: "logic-circuit",
      title: "שערים משולבים",
      inputs: [{ id: "A" }, { id: "B", value: 1 }],
      gates: [
        { id: "n1", type: "nand", inputs: ["A", "B"] },
        { id: "n2", type: "nor", inputs: ["A", "B"] },
        { id: "Y", type: "xnor", inputs: ["n1", "n2"], label: "F" },
      ],
    },
  },
  {
    name: "geometry2d — FBD: block on an incline (mechanics)",
    raw: {
      v: 1,
      kind: "geometry2d",
      title: "גוף על מישור משופע",
      xRange: [-1, 8],
      yRange: [-1, 6],
      grid: false,
      axes: false,
      items: [
        {
          type: "incline",
          x: 0,
          y: 0,
          run: 6,
          angle: 30,
          face: "right",
          angleLabel: "θ",
          block: { at: 0.5, size: 1.1, label: "m" },
        },
        {
          type: "vector",
          x1: 3.6,
          y1: 2.2,
          x2: 3.6,
          y2: 0.2,
          label: "mg",
          color: "accent",
        },
        {
          type: "vector",
          x1: 3.6,
          y1: 2.2,
          x2: 2.75,
          y2: 3.7,
          label: "N",
          color: "success",
        },
        {
          type: "vector",
          x1: 3.6,
          y1: 2.2,
          x2: 4.8,
          y2: 2.9,
          label: "f",
          color: "warning",
        },
      ],
    },
  },
  {
    name: "geometry2d — statics: simply-supported beam (pin + roller)",
    raw: {
      v: 1,
      kind: "geometry2d",
      title: "קורה נתמכת",
      xRange: [-1, 9],
      yRange: [-2, 4],
      grid: false,
      axes: false,
      items: [
        { type: "segment", x1: 0, y1: 1, x2: 8, y2: 1, color: "textMuted" },
        { type: "support", x: 0, y: 1, kind: "pin", label: "A" },
        { type: "support", x: 8, y: 1, kind: "roller", label: "B" },
        {
          type: "vector",
          x1: 4,
          y1: 3.2,
          x2: 4,
          y2: 1.2,
          label: "P",
          color: "accent",
        },
        {
          type: "dimension",
          x1: 0,
          y1: 1,
          x2: 8,
          y2: 1,
          offset: -1.4,
          label: "L",
        },
      ],
    },
  },
  {
    name: "geometry2d — SHM: spring–mass on a wall",
    raw: {
      v: 1,
      kind: "geometry2d",
      title: "מסה על קפיץ",
      xRange: [-1, 8],
      yRange: [-1, 4],
      grid: false,
      axes: false,
      items: [
        { type: "wall", x: 0, y: 0, h: 3, face: "right", label: "" },
        { type: "ground", y: 0 },
        {
          type: "spring",
          x1: 0,
          y1: 1.5,
          x2: 4,
          y2: 1.5,
          coils: 8,
          label: "k",
        },
        {
          type: "polygon",
          points: [
            [4, 0.7],
            [5.6, 0.7],
            [5.6, 2.3],
            [4, 2.3],
          ],
          fill: true,
          color: "accent",
          label: "m",
        },
        {
          type: "vector",
          x1: 5.6,
          y1: 1.5,
          x2: 7,
          y2: 1.5,
          label: "x",
          color: "warning",
        },
      ],
    },
  },
  {
    name: "circuit — RC low-pass (battery + R + C + ground)",
    raw: {
      v: 1,
      kind: "circuit",
      title: "מעגל RC",
      components: [
        { type: "battery", at: [0, 4], to: [0, 0], label: "9V" },
        { type: "resistor", at: [0, 0], to: [6, 0], label: "R 1kΩ" },
        { type: "capacitor", at: [6, 0], to: [6, 4], label: "C 1µF" },
        { type: "wire", at: [6, 4], to: [0, 4] },
        { type: "ground", at: [0, 4] },
      ],
    },
  },
  {
    name: "circuit — voltage divider (R1/R2 + tapped output)",
    raw: {
      v: 1,
      kind: "circuit",
      title: "מחלק מתח",
      components: [
        { type: "source", at: [0, 4], to: [0, 0], label: "Vin" },
        { type: "wire", at: [0, 0], to: [3, 0] },
        { type: "resistor", at: [3, 0], to: [3, 2], label: "R1" },
        { type: "resistor", at: [3, 2], to: [3, 4], label: "R2" },
        { type: "wire", at: [3, 4], to: [0, 4] },
        { type: "wire", at: [3, 2], to: [6, 2] },
        { type: "box", at: [6, 2], to: [8, 2], label: "Vout" },
        { type: "ground", at: [0, 4] },
      ],
    },
  },
  {
    name: "circuit — LED indicator (AC source, diode, switch, lamp)",
    raw: {
      v: 1,
      kind: "circuit",
      title: "מחוון LED",
      components: [
        { type: "battery", at: [0, 3], to: [0, 0], label: "5V" },
        { type: "resistor", at: [0, 0], to: [3, 0], label: "330Ω" },
        { type: "led", at: [3, 0], to: [3, 3], label: "LED" },
        { type: "switch", at: [3, 3], to: [1, 3], label: "S1", closed: false },
        { type: "wire", at: [1, 3], to: [0, 3] },
        { type: "ground", at: [0, 3] },
      ],
    },
  },
];
